--- #YAML:1.0
name: UWO-Student
abstract: >
  Provides Perl object representation of a University of Western Ontario
  student
version: 0.03
author:
  - 'Jonathan Yu <frequency@cpan.org>'
license: bsd
distribution_type: module
urls:
  license: http://opensource.org/licenses/bsd-license.php
build_requires:
  Test: 0
  Test::More: 0.62
requires:
  Carp: 1.04
  overload: 0
provides:
  UWO::Student:
    file: lib/UWO/Student.pm
    version: 0.03
generated_by: hand
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
